language: python
python:
- '3.6'
env:
- TOXENV=docs
- TOXENV=py36
install:

script:

jobs:
  include:
    - stage: 'Elasticsearch test'
      env: TOXENV=py36 ES_VERSION=7.0.0-linux-x86_64
    - env: TOXENV=py36 ES_VERSION=6.6.2
    - env: TOXENV=py36 ES_VERSION=6.3.2
    - env: TOXENV=py36 ES_VERSION=6.2.4
    - env: TOXENV=py36 ES_VERSION=6.0.1
    - env: TOXENV=py36 ES_VERSION=5.6.16

deploy:
  provider: pypi
  user: yelplabs
  password:
    secure: TpSTlFu89tciZzboIfitHhU5NhAB1L1/rI35eQTXstiqzYg2mweOuip+MPNx9AlX3Swg7MhaFYnSUvRqPljuoLjLD0EQ7BHLVSBFl92ukkAMTeKvM6LbB9HnGOwzmAvTR5coegk8IHiegudODWvnhIj4hp7/0EA+gVX7E55kEAw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Yelp/elastalert
    branch: master
